apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab-web
  namespace: homelab-web
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: homelab-web-oauth2-errors@kubernetescrd,homelab-web-oauth2-forward-auth@kubernetescrd
spec:
  rules:
    - host: portal.dev.homelab.local
      http:
        paths:
          - path: /oauth2/
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homelab-web
                port:
                  number: 80
