apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-wordpress
  namespace: homelab-wordpress
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
