apiVersion: v1
kind: Secret
metadata:
    name: my-service-wordpress-db
    namespace: my-service
type: Opaque
stringData:
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:uLgY+LOx6w==,iv:QrzDH4i0gOmGA0fPR/ZvZMzWZWHLcz9K+acK/Vbpsos=,tag:IPZJnObF9Rf5E+RvSnYyfg==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:ZrHhDfjOhY2RtAKHCxRS6K7mYJQ6aSTiNFjg7aARllE=,iv:0g59+jD/guQs+g07d80FwV/rfFEn3tOPrSOyngWKCJQ=,tag:4BGD+uunIba5gYNboQJKsQ==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:pJaZ+kQ=,iv:+6S0ltiKcgKmlAVwq8LRMk9WWby7Q5vZaaiE+xS5qwg=,tag:12wJ/4Zcx4nN1AMd4uz2OQ==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:AP8Rr4kYAE0826kN/13dIB1UyPAOl9/FfP57htfN/+A=,iv:Iu0Rx+M0KoOc05CrKNxfEDUaPWorEoICoV+gAnm+MLw=,tag:X6qSNpcXA+WCBK80h24fCQ==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVmZoaXF4M3B1MTJmUlI2
            RTk2cGt1OE5rcjNMdXJ6OHc0ZUJUUzQ5QUFRCkFjRTNkWXYyaGdRTnU3ck5TV0p1
            UG1pcWhHNzRMOWpmYUdtQlJpN1M4bjQKLS0tIG53SXFQbWtTUXhzRlpFQ3FWazFR
            UU9rZzFwNVk1N2MrQnYxUVNoNUFyL00KubTHh+IASMWLH2N1TlPl3AQIPNSqoEeB
            DMOFWIQEKlwx2Av/4596dvJUJ/GEP3M0JAYB4yRK0alFsD3jlSljrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T11:39:27Z"
    mac: ENC[AES256_GCM,data:bPNNkLRKBOA8d6YGnXNcQJvS/tJFIk282GG2UeoCcLB2MSxtibruqsB1pKAtpwZN2TgJt57zLpum8aYOfHc9dfVkmwJgqv2gtyK9RBdPdmnEBjQQqPrEZ/VRCCFL9xgTruqe6BVkwWn4bkKe/Q6RX1FTrTUU6SzBYzwy+3apOIA=,iv:NWNZk/mIR39fX8lZMETPKcsm/31OD83PI1iRfi6YUW8=,tag:WBMcWJd0kdGrpUw3HjDfRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
