apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: wordpress-db-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - wordpress-db-secret.enc.yaml
