apiVersion: v1
kind: Secret
metadata:
    name: my-service-wordpress-db
    namespace: my-service
type: Opaque
stringData:
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:VxfS9+AVjg==,iv:ozOVgCZ5XzDHM0nMJrkbxHw/NWtfesgmFo6wGouvmBk=,tag:t90+1dVIjFebAh8WfsbsbA==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:Y5x2d1pUn+3uvKY4XRxxaT4GSaiOS9QlJFdjdlYyyJo=,iv:rT3FJisCS7F57UAxXNnIRT0/oXpRBTBuEKWhSNAxzfY=,tag:/Dn2u+o/dzNkyZO5FKZEnw==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:zGJJQAQ=,iv:qe0fkDTEfckyOZy7VzXDC8fM/idFMhThY3VuWFP2Sr4=,tag:uVvzwOTVPsGirEFEHg2ZwQ==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:SPSD3foVRE2e0I/o80jomZd4+N73yU0vUJSxJk4eeMk=,iv:cpw7m//uE+loajDn+T9oghxoTWtSf44BviShFCDxbC4=,tag:tUToQT0rOs0EWI1+CQXOug==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSXlwMTJmc0xVN1hIZkRB
            SjNQMUdtREJ0YkZGaXBnUHJHaWZIeXBEejJvCkJhOTA3cHZSN1pPN1NHNHkwRFNE
            WTdXV0xDVXRGaUhGbGNqVWpIN2dIOU0KLS0tIHhhUTRRbmhSSWk5Qmx5c3pEYkJD
            ZkVtSXBWT2ZQeHNjS1BGb1Fic25UTmcK1gOVF5x72fQV2A41Ctx7K6BADJDc4e0v
            WaGCzA02CE8wC0gADunMdvtuTXfEKEvUeyJTi/6n5syNU9n8dsKhnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T11:39:27Z"
    mac: ENC[AES256_GCM,data:89qjKm+eZijCNNXJ3Rl6utxQQlJ4tO9/LjhuhGmC7ZeVVYCvKWl2S3cS1HHgDmB/GGOGbQPHPhC4ewga3aRPCcrsoh87mvTF7k8TPszAnlj4gnNRr5qy3qa/4Su0MVf3P8NTeZZ5nlJUO//1EeNHD2Bhve2Nyoj9XVR/eZk3Fkc=,iv:00t+/8dLNcJ7PzJZXykVAdbsks/zhB38Y0iNJZMNOwk=,tag:arKPKGPjC3UZ0XSYJOVD2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
