apiVersion: v1
kind: Secret
metadata:
    name: homelab-api-ghcr-read
    namespace: homelab-api
type: Opaque
stringData:
    GHCR_READ_TOKEN: ENC[AES256_GCM,data:DMqRfp8qlMhdSjV7PcDr6Ks7yIe4qs+TV0qmP+/vwwtR70HB4BsEBg==,iv:ShW/D398nK2z+99LQK1uB0N0KA1r1pr+BdboL8eyjWQ=,tag:fbIavXNCdr83k6E/Lq/j2w==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTUorRm85RGNRQ2FSVEk4
            cmtyOHVXcW5lVU95eXRJTEVqNEJlTlkyKzI0CmJEMDY1a0VxMlJsSjNCc2EvRms5
            YzRqaWNBeFNiWmVxWTkzRHQ5TGdnZVUKLS0tIHJwdkVDUU43enJvRlZuK0VxNHd0
            bVZHSjBuL081dXRla0lONzNqZS9jL1UK2hCO5+nEgdRBxKNN0V9CZszKI81b88EJ
            +NC3maR4RUoCNbssxfohoep7OIX0V5MmaLG0EKNaC96gyxhUcgzUlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T12:32:39Z"
    mac: ENC[AES256_GCM,data:nj/mdODx84uDLzC7xMg/PPd3g6koqHqDNEnMwMNfDgsq6JETZP8669Cr8JEKkR9GKB84Kzb1PLHBmbyWHhan5kxalGtbm9aKH6tAMOWhf7K5UMu1hPkAUa9sOWUP27I4w02F0cqmuFK6RjWmXMsJlSz1gQnLtfeHY821HsHc780=,iv:hTsxw3TpLls3VGr7qiUpQGxc2HntYpyx8MlYWA3kicE=,tag:zUp/GVzIcfXS1lq6m7OTYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
