apiVersion: v1
kind: Secret
metadata:
    name: homelab-api-ghcr-read
    namespace: homelab-api
type: Opaque
stringData:
    GHCR_READ_TOKEN: ENC[AES256_GCM,data:8Tw3hfIpPmJCxZdi0gJCf8jrG5N3+7+PAXPE9HIopSvlOkXGF5V/pQ==,iv:eR3y60yF4qdpOl/KmBd1wYntoW/MZjIvf/GkvSQXLmU=,tag:xkKVpjlIwFYDwQglgVqguA==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWb2V0RmRac1lRbERkYjF5
            Sy90WTZuUktGOFVRaWp4VmVNVDZ3ZGFZZUVzCnZ2TkcyQUVXWWxjOUVHbnVmZXEr
            WTZYeGhmQktEK0lUbWZtYlNybDRBVzAKLS0tIEEvWTJ6NWpBblZYNHBzR3JIeGFQ
            MDUzSkVSRG1idG4yZkkwRkJzTTFvVjgKyAHxj0ElfsS7+DL2AEFQgbEAAqhbSY+Q
            PS1UuPZg+SseJw9+NDpUQF1w4vvnPqSb/O2aIswVe5kbElSkITfDCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T11:32:00Z"
    mac: ENC[AES256_GCM,data:MAd7EChPf+MyLesgpLz6a/YYDGsJIKVyGaahTXOg1ULvPsbu+PO7Ar+5CcNzp8SxAUkBWQGGDW0UFq/XGhoG4thjWTION1enTpteVGltAtoZCuEgx668UP554KsGdPagMmmFAxj3XGMjLqOA/Pe93ebdCrPClKW+BkDJnbw4fac=,iv:8iBWXoOB+ZVYm1F980iTYP0D9LlQ7cl0WZ0AU4hgGLU=,tag:r7nQvOJcvLlwDrhTIbnX+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
