apiVersion: v1
kind: Secret
metadata:
    name: homelab-api-github-actions
    namespace: homelab-api
type: Opaque
stringData:
    PORTAL_GITHUB_ACTIONS_TOKEN: ENC[AES256_GCM,data:wbOf/8iceHEiBGPxexL3me9G+vbt7DkLMb0L7PKEFZ1wNEElrZauNw==,iv:t+P+hWkpDDh8tsJQM1EvJpXAiMtAKbJnX8PO1eWxzTM=,tag:ZTgvb8TZ2M0yIbSkNiC9yw==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b1FTSWNsazk2Qy9JVHNV
            M3VzYVU4TjI2dGdrcG1YU3Rvc0ZsMFZyK1hvCjJzOWZMeG80czdUeW53UkVaeVJS
            REdDUmNWNk8zWmUrOXBOQUZVTThocWMKLS0tICs4b1hYd3gwbjNHeXFkRTkreStT
            QXh4ZXo2TDB5cFZMVFRaUVJkWDRja0EKJ37Lm0Bim9+XuBTielnw2X2ypx6JA+b8
            QP7dEphqYdUce4nOx+YCD3FnPkuomCOeEjCq+kzjMw9gZr5Fc/9VZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T13:26:26Z"
    mac: ENC[AES256_GCM,data:sQdJPwxOE6NQgwlthYnn8ENzPszdYO3RIQg8Zyb4yo/KgAgZUWbjwG/PNVNtlxc+b2i9ujxeaXiVorAYIoXXbcflv4/Eigy+QUIfZ2plFgPqnX9/tGU07oCUbCCi3C6OLg56gd8FdJcGEQJxadbqZypeNW3mW/GWHK03jy9Yq+Y=,iv:sqybVcTy5tiKW6+iFD1jR4tDJ2iV8KqBGgVJJm6EDro=,tag:DtWoBXDvPFKKHB5GYS95YA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
