apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: github-actions-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - github-actions-secret.enc.yaml
