apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  homelab.env: dev
patches:
  - path: patch-deployment.yaml
  - path: patch-catalog-sync-cronjob.yaml
  - path: patch-migration-job.yaml
