apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
generators:
  - ghcr-read-token-secret-generator.yaml
  - git-github-token-secret-generator.yaml
  - postgres-secret-generator.yaml
  - github-actions-secret-generator.yaml
commonLabels:
  homelab.env: dev
patches:
  - path: patch-deployment.yaml
  - path: patch-catalog-sync-cronjob.yaml
  - path: patch-migration-job.yaml
