apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-api
  namespace: homelab-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/wlodzimierrr/homelab-api:sha-cd76e5907910d89a50a9ad93a635b726007fde5e
          env:
            - name: APP_ENV
              value: dev
            - name: LOG_LEVEL
              value: debug
