apiVersion: batch/v1
kind: Job
metadata:
  name: homelab-api-migrate
  namespace: homelab-api
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/wlodzimierrr/homelab-api:sha-0087d770e519262884dab2e09524ebb4cad298dd
