apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-api
  namespace: homelab-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/wlodzimierrr/homelab-api:sha-6904464d0c1890629101d845926534e02110b89c
          env:
            - name: APP_ENV
              value: dev
            - name: LOG_LEVEL
              value: debug
            - name: PORTAL_GITHUB_ACTIONS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homelab-api-github-actions
                  key: PORTAL_GITHUB_ACTIONS_TOKEN
            - name: GIT_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homelab-api-git-github
                  key: GIT_GITHUB_TOKEN
                  optional: true
            - name: GHCR_READ_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homelab-api-ghcr-read
                  key: GHCR_READ_TOKEN
                  optional: true
