apiVersion: batch/v1
kind: Job
metadata:
  name: homelab-api-migrate
  namespace: homelab-api
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/wlodzimierrr/homelab-api:sha-7f8822fad00f2b94b079dcf671938f986045d0d2
