apiVersion: batch/v1
kind: CronJob
metadata:
  name: homelab-api-catalog-sync
  namespace: homelab-api
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: catalog-sync
              image: ghcr.io/wlodzimierrr/homelab-api:sha-541db192d7f15265720d3a58a664365876d2c5d3
