apiVersion: batch/v1
kind: CronJob
metadata:
  name: homelab-api-catalog-sync
  namespace: homelab-api
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: catalog-sync
              image: ghcr.io/wlodzimierrr/homelab-api:sha-fc6e655a7750a53d6ac7d71834238253c1acca25
