apiVersion: batch/v1
kind: Job
metadata:
  name: homelab-api-migrate
  namespace: homelab-api
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/wlodzimierrr/homelab-api:sha-1c2dfe36a193e5a5b769ea8aa76c36bf5ef156ea
