apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homelab-api-app.yaml
  - homelab-web-app.yaml
  - loki-app.yaml
  - monitoring-app.yaml
  - monitoring-ingress-app.yaml
  - promtail-app.yaml
  - scaffold-smoke-app.yaml
