apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-service-dev
  namespace: argocd
spec:
  project: my-service
  source:
    repoURL: https://github.com/wlodzimierrr/homelab-workloads.git
    targetRevision: main
    path: apps/my-service/envs/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: my-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
