apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail-dev
  namespace: argocd
spec:
  project: homelab-monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.17.0
    helm:
      releaseName: promtail
      values: |
        resources:
          requests:
            cpu: 50m
            memory: 96Mi
          limits:
            cpu: 200m
            memory: 256Mi

        config:
          clients:
            - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
          snippets:
            pipelineStages:
              - cri: {}
            extraRelabelConfigs:
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
                regex: (.+)
                target_label: app
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_label_app
                regex: (.+)
                target_label: app
              - action: replace
                source_labels:
                  - app
                  - __meta_kubernetes_pod_name
                regex: ^$;(.+)
                replacement: $1
                target_label: app
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
