apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scaffold-smoke-dev
  namespace: argocd
spec:
  project: scaffold-smoke
  source:
    repoURL: https://github.com/wlodzimierrr/homelab-workloads.git
    targetRevision: main
    path: apps/scaffold-smoke/envs/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: scaffold-smoke
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
