apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-prod
  namespace: argocd
spec:
  project: homelab-bootstrap
  source:
    repoURL: https://github.com/wlodzimierrr/homelab-workloads.git
    targetRevision: main
    path: environments/prod/workloads
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
