apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount-backend.yaml
  - role-backend-kube-api-read.yaml
  - rolebinding-backend-kube-api-read.yaml
  - deployment.yaml
  - service.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - migration-job.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-dns-egress.yaml
  - networkpolicy-allow-ingress.yaml
  - networkpolicy-allow-postgres-ingress.yaml
  - networkpolicy-allow-egress-postgres.yaml
