apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-platform-and-web
  namespace: homelab-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: homelab-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8000
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: homelab-web
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8000
