apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homelab-api
  namespace: homelab-api
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homelab-api
  namespaceSelector:
    matchNames:
      - homelab-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
