apiVersion: batch/v1
kind: CronJob
metadata:
  name: homelab-api-catalog-sync
  namespace: homelab-api
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: catalog-sync
              image: ghcr.io/wlodzimierrr/homelab-api:sha-6beb5ac154c3e0df2009eefd904b6f9c33318412
