apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-next
  namespace: portfolio-next
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/wlodzimierrr/portfolio-next:latest
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: prod
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
