apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homelab-wordpress-wp-content
  namespace: homelab-wordpress
  labels:
    app.kubernetes.io/name: homelab-wordpress
    app.kubernetes.io/component: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
