apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-next
  namespace: portfolio-next
  labels:
    app.kubernetes.io/name: portfolio-next
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: portfolio-next.dev.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-next
                port:
                  number: 80
