apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio-next
  namespace: portfolio-next
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: portfolio-next
  namespaceSelector:
    matchNames:
      - portfolio-next
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
