apiVersion: v1
kind: Service
metadata:
  name: portfolio-next
  namespace: portfolio-next
  labels:
    app.kubernetes.io/name: portfolio-next
    app.kubernetes.io/instance: portfolio-next
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: portfolio-next
  ports:
    - name: http
      port: 80
      targetPort: http
