apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount-web.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-dns-egress.yaml
  - networkpolicy-allow-ingress.yaml
  - networkpolicy-allow-egress-api.yaml
